<?php
/**
 * Copyright (c) 2025 Flipdev. All rights reserved.
 */
declare(strict_types=1);

namespace FlipDev\Seo\Model\RobotsTxt;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\Filesystem;
use Magento\Store\Model\StoreManagerInterface;
use Psr\Log\LoggerInterface;

class Generator
{
    private const CONFIG_ENABLED = 'flipdev_seo/robots_txt/enabled';
    private const CONFIG_CONTENT = 'flipdev_seo/robots_txt/content';
    private const CONFIG_AUTO_SITEMAP = 'flipdev_seo/robots_txt/auto_sitemap';
    private const CONFIG_CUSTOM_SITEMAPS = 'flipdev_seo/robots_txt/custom_sitemaps';
    private const CONFIG_SITEMAP_ENABLED = 'flipdev_seo/xml_sitemap/enabled';

    public function __construct(
        private ScopeConfigInterface $scopeConfig,
        private StoreManagerInterface $storeManager,
        private Filesystem $filesystem,
        private LoggerInterface $logger
    ) {
    }

    /**
     * Check if robots.txt management is enabled
     */
    public function isEnabled(): bool
    {
        return $this->scopeConfig->isSetFlag(self::CONFIG_ENABLED);
    }

    /**
     * Generate and write robots.txt file
     */
    public function generate(): bool
    {
        if (!$this->isEnabled()) {
            return false;
        }

        try {
            $content = $this->buildContent();
            $this->writeFile($content);
            return true;
        } catch (\Exception $e) {
            $this->logger->error('FlipDev_Seo: Error generating robots.txt', [
                'error' => $e->getMessage()
            ]);
            return false;
        }
    }

    /**
     * Build robots.txt content
     */
    public function buildContent(): string
    {
        $lines = [];

        // Get base content from config
        $baseContent = $this->scopeConfig->getValue(self::CONFIG_CONTENT);
        if ($baseContent) {
            $lines[] = trim($baseContent);
        } else {
            // Default content if none configured
            $lines[] = "User-agent: *";
            $lines[] = "Disallow: /checkout/";
            $lines[] = "Disallow: /customer/";
            $lines[] = "Disallow: /catalogsearch/";
            $lines[] = "Disallow: /*?";
            $lines[] = "";
        }

        $lines[] = "";

        // Auto-add sitemap URLs
        if ($this->scopeConfig->isSetFlag(self::CONFIG_AUTO_SITEMAP)) {
            $sitemapUrls = $this->getSitemapUrls();
            foreach ($sitemapUrls as $url) {
                $lines[] = "Sitemap: " . $url;
            }
        }

        // Add custom sitemap URLs
        $customSitemaps = $this->scopeConfig->getValue(self::CONFIG_CUSTOM_SITEMAPS);
        if ($customSitemaps) {
            $customUrls = array_filter(array_map('trim', explode("\n", $customSitemaps)));
            foreach ($customUrls as $url) {
                if (!empty($url) && filter_var($url, FILTER_VALIDATE_URL)) {
                    $lines[] = "Sitemap: " . $url;
                }
            }
        }

        // Add generator comment
        $lines[] = "";
        $lines[] = "# Generated by FlipDev SEO for Magento 2";

        return implode("\n", $lines);
    }

    /**
     * Get sitemap index URLs for all active stores
     * Points to the main sitemap index which references all sub-sitemaps
     */
    private function getSitemapUrls(): array
    {
        $urls = [];

        // Check if custom sitemap is enabled
        if (!$this->scopeConfig->isSetFlag(self::CONFIG_SITEMAP_ENABLED)) {
            return $urls;
        }

        foreach ($this->storeManager->getStores() as $store) {
            if (!$store->getIsActive()) {
                continue;
            }

            $storeCode = $store->getCode();
            $baseUrl = rtrim($store->getBaseUrl(), '/');
            // Point to the sitemap index file (which contains all sub-sitemaps)
            $sitemapFile = $storeCode . '-sitemap.xml';

            $urls[] = $baseUrl . '/' . $sitemapFile;
        }

        return array_unique($urls);
    }

    /**
     * Write robots.txt file to pub directory
     */
    private function writeFile(string $content): void
    {
        $directory = $this->filesystem->getDirectoryWrite(DirectoryList::PUB);
        $directory->writeFile('robots.txt', $content);
    }

    /**
     * Get current robots.txt content (for display)
     */
    public function getCurrentContent(): string
    {
        try {
            $directory = $this->filesystem->getDirectoryRead(DirectoryList::PUB);
            if ($directory->isExist('robots.txt')) {
                return $directory->readFile('robots.txt');
            }
        } catch (\Exception $e) {
            // File doesn't exist or can't be read
        }

        return '';
    }
}
