<?php
declare(strict_types=1);

/** @var \FlipDev\Seo\Block\StructuredData\TwitterCards $block */
$_product = $block->getProduct();
$_imageUrl = $block->getProductImageUrl($_product);
$_description = $block->cleanString($this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getDescription(), 'description'));
$_description = mb_substr($_description, 0, 200);
?>
<meta name="twitter:card" content="product" />
<meta name="twitter:site" content="<?php echo $block->escapeHtmlAttr($block->getConfig('flipdev_seo/twittercards/twittersite')) ?>" />
<meta name="twitter:title" content="<?php echo $block->cleanString($_product->getName()) ?>" />
<meta name="twitter:description" content="<?php echo $_description ?>" />
<meta name="twitter:image" content="<?php echo $_imageUrl ?>" />
<meta name="twitter:data1" content="<?php echo $block->getStartingPrice($_product); ?>" />
<meta name="twitter:label1" content="PRICE" />
<meta name="twitter:data2" content="<?php echo $block->getConfig('shipping/origin/country_id') ?>" />
<meta name="twitter:label2" content="LOCATION" />